services:
  ros-dev:
    build:
      context: .
      dockerfile: ${ROS_VERSION-humble}.Dockerfile
    image: aros-legal-${ROS_VERSION:-humble}
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=${INSTANCE:-1}
    volumes:
      - ./data:/root/data
      - ${WORKSPACE_PATH:-./workspace}:/home/ultra/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix

    network_mode: "host"  #Da problema com os nós, precisa mudar ROS_DOMAIN
    #ipc: host  #Costuma dar problema com gazebo por conta da RAM compartilhada. 
    #networks:
    #  - rmf_network
      
    shm_size: '2gb' #Shared Memory Size. Aloca mais memória pro container
    tty: true
    stdin_open: true
    command: bash

#networks:
#  rmf_network:
#    external: true
